import assert from "node:assert/strict";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = fileURLToPath(new URL("../", import.meta.url));
const check = process.argv.includes("--check");
const result = await build({
  absWorkingDir: root,
  entryPoints: ["action/src/main.ts"],
  outfile: "action/dist/index.cjs",
  bundle: true,
  platform: "node",
  target: "node24",
  format: "cjs",
  legalComments: "linked",
  write: false,
  metafile: true,
  banner: { js: "// Generated by npm run action:build. Edit action/src/ and src/, then rebuild." },
});
// Every runtime dependency must be bundled; only Node built-ins may stay external.
const { isBuiltin } = await import("node:module");
for (const output of Object.values(result.metafile.outputs)) {
  for (const dependency of output.imports)
    assert(isBuiltin(dependency.path), `Unbundled dependency: ${dependency.path}`);
}
const packagePaths = new Set();
for (const input of Object.keys(result.metafile.inputs)) {
  if (!input.startsWith("node_modules/")) continue;
  const parts = input.split("/");
  packagePaths.add(parts.slice(0, parts[1].startsWith("@") ? 3 : 2).join("/"));
}
const notices = ["Third-party notices for the generated Syngraphe GitHub Action.\n"];
for (const directory of [...packagePaths].sort()) {
  const manifest = JSON.parse(await readFile(path.join(root, directory, "package.json"), "utf8"));
  let license;
  for (const filename of ["LICENSE", "LICENSE.md", "LICENSE.txt"]) {
    try {
      license = await readFile(path.join(root, directory, filename), "utf8");
      break;
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
  }
  assert(license, `Missing license for bundled dependency ${manifest.name}`);
  notices.push(
    `${manifest.name}@${manifest.version} (${manifest.license})\n\n${license.replaceAll("\r\n", "\n").trim()}\n`,
  );
}
const noticeText = `${notices.join("\n")}\n`;
const generated = [
  ...result.outputFiles,
  {
    path: path.join(root, "action/dist/THIRD_PARTY_NOTICES.txt"),
    text: noticeText,
    contents: Buffer.from(noticeText),
  },
];
for (const file of generated) {
  if (check) {
    assert(
      (await readFile(file.path, "utf8")) === file.text,
      `Action bundle drift: ${path.relative(root, file.path)}. Run npm run action:build.`,
    );
  } else {
    await mkdir(path.dirname(file.path), { recursive: true });
    await writeFile(file.path, file.contents);
  }
}
console.log(check ? "Action bundle matches its sources." : "Action bundle generated.");
